# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# Use container based infrastructure for Travis
sudo: false

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.0.x version
  - 7.0
  # aliased to a recent 7.1.x version
  - 7.1
  # aliased to a recent 7.2.x version
  - 7.2
  # aliased to a recent hhvm version
  - hhvm

#Coverity
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "vMCan2hMWKZOmYDRximgj8Z+yQqVNsaA0FJ83eOjVmjjy2xxNVc53u0Qisq/FJf+1aGTz1FIz/xoSeV5tC7Gbpk6J23D98NUMX/6IfrbXl5mvLFyg4kKd8MPo4tonDMalXtbbzaaipYSRDgav/POK0A/NhrT3dmAw8t43jYu47to/uUyQULZDjPQKg/3hcDaEXQ0bXW6JMGnL73Tkx9FbYNHkAbLq8apEUpKDmfe1tyij3J5t29EjJMzFAkDTJ4fDFvFTpoM28WjKagwMQgjfNIaYYKQKtwGMcbua/lrDTxbRf3LSBwRE0oVLWW1g+9gfwEmQN0JsTnQQvzn5iPeKgdu1/ENgVKY6bz66wlMQXPL4QXUPFmZD43uzxjbr28PL9yjcmoQa+S3pgRi5hjoBl0vfKb1xBOkSsMCkxakjdYIVbQ0r6+UbNDsFq21CRsRFFXAkUvnQUpH285uo8IPYoyBM2xIi2Z3YlUjugdnee/m+th2sDRIDRUXZUC7a+BpjabvvlrFpTRH5WqaebtB04D4sH0qwIIR5s24w6MlZyVKBigamboTMg52tFshlE7w1AkWBqa0ZzrIeJvTzvoR6QEoU3r89vo3KKn4TX52ko/gG0HGq49zd2sKvTsJnzPb0Z1+AbSDbI145M7uU6hi5JQcIW9pCPmEgG6T97p3tUg="

# https://docs.travis-ci.com/user/migrating-from-legacy
addons:
  apt:
    packages:
    - uuid-dev
    - build-essential
    - autoconf
    - cmake
    - time
  coverity_scan:
    project:
      name: "ph4r05/php_aho_corasick"
      description: "PHP extension for fast pattern matching using AhoCorasick algorithm"
    notification_email: ph4r05@gmail.com
    build_command:   ./build.sh
    branch_pattern: coverity_scan

script:
  - ./build.sh
  - NO_INTERACTION=1 REPORT_EXIT_STATUS=1 make test TESTS="--show-diff"

# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: hhvm
